=== Khmelov/JD2016/src/by/it/drachyova/jd02_07/Hotel.dtd
<?xml version="1.0" encoding="UTF-8" ?>
        <!ELEMENT Hotel (Name, Stars, Address, Rooms)>
        <!ELEMENT Name (#PCDATA)>
        <!ELEMENT Stars (#PCDATA)>
        <!ELEMENT Address (#PCDATA)>
        <!ELEMENT Rooms (Room)+>
        <!ELEMENT Room (Type, Area, Price)>
        <!ELEMENT Type (#PCDATA)>
        <!ELEMENT Area (#PCDATA)>
        <!ELEMENT Price (#PCDATA)>

=== Khmelov/JD2016/src/by/it/drachyova/jd02_07/Hotel.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE Hotel SYSTEM "Hotel.dtd" >
<Hotel>
    <Name>Villas Resort</Name>
    <Stars>4</Stars>
    <Address>Localita Santa Giusta, 09040 , Castiadas, Sardegna, Italy</Address>
    <Rooms>
        <Room>
            <Type>Classic</Type>
            <Area>20</Area>
            <Price>400</Price>
        </Room>
        <Room>
            <Type>Deluxe</Type>
            <Area>25</Area>
            <Price>489</Price>
        </Room>
        <Room>
            <Type>Suit</Type>
            <Area>30</Area>
            <Price>733</Price>
        </Room>
        <Room>
            <Type>Royal Suit</Type>
            <Area>40</Area>
            <Price>900</Price>
        </Room>
    </Rooms>
</Hotel>
