<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE Persons [
        <!ELEMENT Persons (Person)+>
        <!ELEMENT Person (Email, Password, Nickname, Ads) >
        <!ELEMENT Email (#PCDATA) >
        <!ELEMENT Password (#PCDATA) >
        <!ELEMENT Nickname (#PCDATA) >
        <!ELEMENT Ads (ad)+>
        <!ELEMENT ad (Description,Address,Flat,Flats,Price,Area)>
        <!ELEMENT Description (#PCDATA) >
        <!ELEMENT Address (#PCDATA) >
        <!ELEMENT Flat (#PCDATA) >
        <!ELEMENT Flats (#PCDATA) >
        <!ELEMENT Price (#PCDATA) >
        <!ELEMENT Area (#PCDATA) >

        ] >
<Persons>
        <Person>
                <Email>
                        post@mail.ru
                </Email>
                <Password>
                        ewqdsacxz
                </Password>
                <Nickname>
                        post
                </Nickname>
                <Ads>
                        <ad>
                                <Description>
                                        Уютная квартира в центре
                                </Description>
                                <Address>
                                        Минск, ул. Гикало, 14, 23
                                </Address>
                                <Flat>4</Flat>
                                <Flats>5</Flats>
                                <Price>55555</Price>
                                <Area>48.6</Area>
                        </ad>
                        <ad>
                                <Description>
                                        Уютная квартира в Уручье
                                </Description>
                                <Address>
                                        Минск, ул. Городецкая, 14, 23
                                </Address>
                                <Flat>24</Flat>
                                <Flats>25</Flats>
                                <Price>77777</Price>
                                <Area>68.6</Area>
                        </ad>
                </Ads>
        </Person>
</Persons>