=== Khmelov/JD2016/src/by/it/kushel/jd02_07/book.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://kushel.it-academy.by/xml/books"
        xmlns:tns="http://kushel.it-academy.by/xml/books"
        elementFormDefault="qualified">
    <element name="books">
        <complexType>
            <sequence>
                <element name="book"
                         type="tns:book"
                         minOccurs="2"
                         maxOccurs="unbounded" />
            </sequence>
        </complexType>
    </element>
    <complexType name="book">
        <sequence>
            <element name="name" type="string" />
            <element name="autor" type="string" />
            <element name="genre" type="string" />
            <element name="numberOfPages" type="positiveInteger" />
            <element name="publicationDate" type="positiveInteger" />
            <element name="volume" type="positiveInteger" />
            <element name="number" type="tns:number" />
        </sequence>
        <attribute name="number" type="tns:number" use="required" />

    </complexType>
    <complexType name="number">
        <sequence>
            <element name="numberOfBooksInLibrary" type="positiveInteger" />
            <element name="numberOfAvailableBooks" type="positiveInteger" />
        </sequence>
    </complexType>
</schema>

=== Khmelov/JD2016/src/by/it/kushel/jd02_07/books.xml
<?xml version="1.0" encoding="UTF-8"?>
<books xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns="http://kushel.it-academy.by/xml/books"
       xsi:schemaLocation="http://kushel.it-academy.by/xml/books book.xsd">
    <book number="0001">
        <name>Java 8</name>
        <autor>Schildt</autor>
        <genre>technical publications</genre>
        <numberOfPages>999</numberOfPages>
        <publicationDate>2015</publicationDate>
        <volume>1</volume>
        <number>
            <numberOfBooksInLibrary>5</numberOfBooksInLibrary>
            <numberOfAvailableBooks>5</numberOfAvailableBooks>
        </number>
    </book>

    <book number="0002">
        <name>Java 2</name>
        <autor>Horstmann</autor>
        <genre>technical publications</genre>
        <numberOfPages>600</numberOfPages>
        <publicationDate>2010</publicationDate>
        <volume>1</volume>
        <number>
            <numberOfBooksInLibrary>3</numberOfBooksInLibrary>
            <numberOfAvailableBooks>3</numberOfAvailableBooks>
        </number>
    </book>
    <book number="0003">
        <name>Java 2</name>
        <autor>Horstmann</autor>
        <genre>technical publications</genre>
        <numberOfPages>590</numberOfPages>
        <publicationDate>2010</publicationDate>
        <volume>2</volume>
        <number>
            <numberOfBooksInLibrary>3</numberOfBooksInLibrary>
            <numberOfAvailableBooks>3</numberOfAvailableBooks>
        </number>
    </book>
</books>
