<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE HorseRace [
        <!ELEMENT HorseRace (Clients|Races|BookMaker|Horses)*>
        <!ATTLIST HorseRace
                date CDATA #REQUIRED>
        <!ELEMENT Clients (Client)*>
        <!ELEMENT Client (Age|Vip|Bets)*>
        <!ATTLIST Client
                name CDATA #REQUIRED
                sex CDATA #REQUIRED>
        <!ELEMENT Age (#PCDATA)>
        <!ELEMENT Vip (#PCDATA)>
        <!ELEMENT Bets (Bet)*>
        <!ELEMENT Bet (Race|Horse|Sum|Payout)*>
        <!ATTLIST Bet
                time CDATA #REQUIRED>
        <!ELEMENT Race (RaceNumber|Horses|Winner)*>
        <!ATTLIST Race
                time CDATA #REQUIRED>
        <!ELEMENT RaceNumber (#PCDATA)>
        <!ELEMENT Horses (Horse)*>
        <!ELEMENT Horse (Name|Odds)*>
        <!ELEMENT Name (#PCDATA)>
        <!ELEMENT Odds (#PCDATA)>
        <!ELEMENT Winner (Horse)*>
        <!ELEMENT Sum (#PCDATA)>
        <!ELEMENT Payout (#PCDATA)>
        <!ELEMENT Races (Race)*>
        <!ELEMENT BookMaker (Name|Bets|Profit)*>
        <!ELEMENT Profit (#PCDATA)>
        ]>
<HorseRace date="27 июня 2016 г.">
    <Clients>
        <Client name="Лудоман Андрей Иванович" sex="Мужской">
            <Age>
                44
            </Age>
            <Vip>
                true
            </Vip>
            <Bets>
                <Bet time="13:59:44">
                    <Race time="14:00">
                        <RaceNumber>
                            1
                        </RaceNumber>
                        <Horses>
                            <Horse>
                                <Name>
                                    Искра
                                </Name>
                                <Odds>
                                    2.5
                                </Odds>
                            </Horse>
                            <Horse>
                                <Name>
                                    Фаворит
                                </Name>
                                <Odds>
                                    1.5
                                </Odds>
                            </Horse>
                            <Horse>
                                <Name>
                                    Пегас
                                </Name>
                                <Odds>
                                    2
                                </Odds>
                            </Horse>
                            <Horse>
                                <Name>
                                    Звезда
                                </Name>
                                <Odds>
                                    5.5
                                </Odds>
                            </Horse>
                        </Horses>
                        <Winner>
                            <Horse>
                                <Name>
                                    Искра
                                </Name>
                                <Odds>
                                    2.5
                                </Odds>
                            </Horse>
                        </Winner>
                    </Race>
                    <Horse>
                        <Name>
                            Искра
                        </Name>
                        <Odds>
                            2.5
                        </Odds>
                    </Horse>
                    <Sum>
                        100
                    </Sum>
                    <Payout>
                        250
                    </Payout>
                </Bet>
                <Bet time="14:22:00">
                    <Race time="14:30">
                        <RaceNumber>
                            2
                        </RaceNumber>
                        <Horses>
                            <Horse>
                                <Name>
                                    Искра
                                </Name>
                                <Odds>
                                    2.5
                                </Odds>
                            </Horse>
                            <Horse>
                                <Name>
                                    Фаворит
                                </Name>
                                <Odds>
                                    1.5
                                </Odds>
                            </Horse>
                            <Horse>
                                <Name>
                                    Пегас
                                </Name>
                                <Odds>
                                    2
                                </Odds>
                            </Horse>
                            <Horse>
                                <Name>
                                    Звезда
                                </Name>
                                <Odds>
                                    5.5
                                </Odds>
                            </Horse>
                        </Horses>
                        <Winner>
                            <Horse>
                                <Name>
                                    Звезда
                                </Name>
                                <Odds>
                                    5.5
                                </Odds>
                            </Horse>
                        </Winner>
                    </Race>
                    <Horse>
                        <Name>
                            Фаворит
                        </Name>
                        <Odds>
                            1.5
                        </Odds>
                    </Horse>
                    <Sum>
                        200
                    </Sum>
                    <Payout>
                        0
                    </Payout>
                </Bet>
            </Bets>
        </Client>
        <Client name="Макаров Егор Батькович" sex="Мужской">
            <Age>
                27
            </Age>
            <Vip>
                false
            </Vip>
            <Bets>
                <Bet time="13:59:22">
                    <Race time="14:00">
                        <RaceNumber>
                            1
                        </RaceNumber>
                        <Horses>
                            <Horse>
                                <Name>
                                    Искра
                                </Name>
                                <Odds>
                                    2.5
                                </Odds>
                            </Horse>
                            <Horse>
                                <Name>
                                    Фаворит
                                </Name>
                                <Odds>
                                    1.5
                                </Odds>
                            </Horse>
                            <Horse>
                                <Name>
                                    Пегас
                                </Name>
                                <Odds>
                                    2
                                </Odds>
                            </Horse>
                            <Horse>
                                <Name>
                                    Звезда
                                </Name>
                                <Odds>
                                    5.5
                                </Odds>
                            </Horse>
                        </Horses>
                        <Winner>
                            <Horse>
                                <Name>
                                    Искра
                                </Name>
                                <Odds>
                                    2.5
                                </Odds>
                            </Horse>
                        </Winner>
                    </Race>
                    <Horse>
                        <Name>
                            Пегас
                        </Name>
                        <Odds>
                            2
                        </Odds>
                    </Horse>
                    <Sum>
                        100
                    </Sum>
                    <Payout>
                        0
                    </Payout>
                </Bet>
                <Bet time="14:23:00">
                    <Race time="14:30">
                        <RaceNumber>
                            2
                        </RaceNumber>
                        <Horses>
                            <Horse>
                                <Name>
                                    Искра
                                </Name>
                                <Odds>
                                    2.5
                                </Odds>
                            </Horse>
                            <Horse>
                                <Name>
                                    Фаворит
                                </Name>
                                <Odds>
                                    1.5
                                </Odds>
                            </Horse>
                            <Horse>
                                <Name>
                                    Пегас
                                </Name>
                                <Odds>
                                    2
                                </Odds>
                            </Horse>
                            <Horse>
                                <Name>
                                    Звезда
                                </Name>
                                <Odds>
                                    5.5
                                </Odds>
                            </Horse>
                        </Horses>
                        <Winner>
                            <Horse>
                                <Name>
                                    Звезда
                                </Name>
                                <Odds>
                                    5.5
                                </Odds>
                            </Horse>
                        </Winner>
                    </Race>
                    <Horse>
                        <Name>
                            Звезда
                        </Name>
                        <Odds>
                            5.5
                        </Odds>
                    </Horse>
                    <Sum>
                        1000
                    </Sum>
                    <Payout>
                        5500
                    </Payout>
                </Bet>
            </Bets>
        </Client>
    </Clients>
    <Races>
        <Race time="14:00">
            <RaceNumber>
                1
            </RaceNumber>
            <Horses>
                <Horse>
                    <Name>
                        Искра
                    </Name>
                    <Odds>
                        2.5
                    </Odds>
                </Horse>
                <Horse>
                    <Name>
                        Фаворит
                    </Name>
                    <Odds>
                        1.5
                    </Odds>
                </Horse>
                <Horse>
                    <Name>
                        Пегас
                    </Name>
                    <Odds>
                        2
                    </Odds>
                </Horse>
                <Horse>
                    <Name>
                        Звезда
                    </Name>
                    <Odds>
                        5.5
                    </Odds>
                </Horse>
            </Horses>
            <Winner>
                <Horse>
                    <Name>
                        Искра
                    </Name>
                    <Odds>
                        2.5
                    </Odds>
                </Horse>
            </Winner>
        </Race>
        <Race time="14:30">
            <RaceNumber>
                2
            </RaceNumber>
            <Horses>
                <Horse>
                    <Name>
                        Искра
                    </Name>
                    <Odds>
                        2.5
                    </Odds>
                </Horse>
                <Horse>
                    <Name>
                        Фаворит
                    </Name>
                    <Odds>
                        1.5
                    </Odds>
                </Horse>
                <Horse>
                    <Name>
                        Пегас
                    </Name>
                    <Odds>
                        2
                    </Odds>
                </Horse>
                <Horse>
                    <Name>
                        Звезда
                    </Name>
                    <Odds>
                        5.5
                    </Odds>
                </Horse>
            </Horses>
            <Winner>
                <Horse>
                    <Name>
                        Звезда
                    </Name>
                    <Odds>
                        5.5
                    </Odds>
                </Horse>
            </Winner>
        </Race>
    </Races>
    <BookMaker>
        <Name>
            Синкевич Денис Сергеевич
        </Name>
        <Bets>
            <Bet time="13:59:22">
                <Race time="14:00">
                    <RaceNumber>
                        1
                    </RaceNumber>
                    <Horses>
                        <Horse>
                            <Name>
                                Искра
                            </Name>
                            <Odds>
                                2.5
                            </Odds>
                        </Horse>
                        <Horse>
                            <Name>
                                Фаворит
                            </Name>
                            <Odds>
                                1.5
                            </Odds>
                        </Horse>
                        <Horse>
                            <Name>
                                Пегас
                            </Name>
                            <Odds>
                                2
                            </Odds>
                        </Horse>
                        <Horse>
                            <Name>
                                Звезда
                            </Name>
                            <Odds>
                                5.5
                            </Odds>
                        </Horse>
                    </Horses>
                    <Winner>
                        <Horse>
                            <Name>
                                Искра
                            </Name>
                            <Odds>
                                2.5
                            </Odds>
                        </Horse>
                    </Winner>
                </Race>
                <Horse>
                    <Name>
                        Пегас
                    </Name>
                    <Odds>
                        2
                    </Odds>
                </Horse>
                <Sum>
                    100
                </Sum>
                <Payout>
                    0
                </Payout>
            </Bet>
            <Bet time="14:23:00">
                <Race time="14:30">
                    <RaceNumber>
                        2
                    </RaceNumber>
                    <Horses>
                        <Horse>
                            <Name>
                                Искра
                            </Name>
                            <Odds>
                                2.5
                            </Odds>
                        </Horse>
                        <Horse>
                            <Name>
                                Фаворит
                            </Name>
                            <Odds>
                                1.5
                            </Odds>
                        </Horse>
                        <Horse>
                            <Name>
                                Пегас
                            </Name>
                            <Odds>
                                2
                            </Odds>
                        </Horse>
                        <Horse>
                            <Name>
                                Звезда
                            </Name>
                            <Odds>
                                5.5
                            </Odds>
                        </Horse>
                    </Horses>
                    <Winner>
                        <Horse>
                            <Name>
                                Звезда
                            </Name>
                            <Odds>
                                5.5
                            </Odds>
                        </Horse>
                    </Winner>
                </Race>
                <Horse>
                    <Name>
                        Звезда
                    </Name>
                    <Odds>
                        5.5
                    </Odds>
                </Horse>
                <Sum>
                    1000
                </Sum>
                <Payout>
                    5500
                </Payout>
            </Bet>
            <Bet time="13:59:44">
                <Race time="14:00">
                    <RaceNumber>
                        1
                    </RaceNumber>
                    <Horses>
                        <Horse>
                            <Name>
                                Искра
                            </Name>
                            <Odds>
                                2.5
                            </Odds>
                        </Horse>
                        <Horse>
                            <Name>
                                Фаворит
                            </Name>
                            <Odds>
                                1.5
                            </Odds>
                        </Horse>
                        <Horse>
                            <Name>
                                Пегас
                            </Name>
                            <Odds>
                                2
                            </Odds>
                        </Horse>
                        <Horse>
                            <Name>
                                Звезда
                            </Name>
                            <Odds>
                                5.5
                            </Odds>
                        </Horse>
                    </Horses>
                    <Winner>
                        <Horse>
                            <Name>
                                Искра
                            </Name>
                            <Odds>
                                2.5
                            </Odds>
                        </Horse>
                    </Winner>
                </Race>
                <Horse>
                    <Name>
                        Искра
                    </Name>
                    <Odds>
                        2.5
                    </Odds>
                </Horse>
                <Sum>
                    100
                </Sum>
                <Payout>
                    250
                </Payout>
            </Bet>
            <Bet time="14:22:00">
                <Race time="14:30">
                    <RaceNumber>
                        2
                    </RaceNumber>
                    <Horses>
                        <Horse>
                            <Name>
                                Искра
                            </Name>
                            <Odds>
                                2.5
                            </Odds>
                        </Horse>
                        <Horse>
                            <Name>
                                Фаворит
                            </Name>
                            <Odds>
                                1.5
                            </Odds>
                        </Horse>
                        <Horse>
                            <Name>
                                Пегас
                            </Name>
                            <Odds>
                                2
                            </Odds>
                        </Horse>
                        <Horse>
                            <Name>
                                Звезда
                            </Name>
                            <Odds>
                                5.5
                            </Odds>
                        </Horse>
                    </Horses>
                    <Winner>
                        <Horse>
                            <Name>
                                Звезда
                            </Name>
                            <Odds>
                                5.5
                            </Odds>
                        </Horse>
                    </Winner>
                </Race>
                <Horse>
                    <Name>
                        Фаворит
                    </Name>
                    <Odds>
                        1.5
                    </Odds>
                </Horse>
                <Sum>
                    200
                </Sum>
                <Payout>
                    0
                </Payout>
            </Bet>
        </Bets>
        <Profit>
            20000
        </Profit>
    </BookMaker>
    <Horses>
        <Horse>
            <Name>
                Искра
            </Name>
            <Odds>
                2.5
            </Odds>
        </Horse>
        <Horse>
            <Name>
                Фаворит
            </Name>
            <Odds>
                1.5
            </Odds>
        </Horse>
        <Horse>
            <Name>
                Пегас
            </Name>
            <Odds>
                2
            </Odds>
        </Horse>
        <Horse>
            <Name>
                Звезда
            </Name>
            <Odds>
                5.5
            </Odds>
        </Horse>
    </Horses>
</HorseRace>